# Generated by Django 3.0.2 on 2020-01-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_csv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='steps_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
